### PR TITLE
chore: use codeclimate for unit test coverage

### PR DESCRIPTION
**Pull request by niekvanstaveren**
**Checklist**

- [ ] tests added
- [ ] commits conform to the [commit guidelines](./CONTRIBUTING.md#commit)
- [ ] documentation updated

### CODE REVIEW

**Comment by cbt1** [comment]
What is the plan here? Unit tests are run both in GitHub Actions and in CircleCI now

**Comment by niekvanstaveren** [comment]
> What is the plan here? Unit tests are run both in GitHub Actions and in CircleCI now

No the plan is to merge this in master and see if it works. The action is not triggered yet, for that it needs to be merged to the default branch. If that works like it should (and I can actually get the reporter id) then I will create another PR for cleanup

**Comment by cbt1** [comment]
Is there going to be another PR/s that move to GitHub Actions for the other jobs on CircleCI as well?

**Review by cbt1 — APPROVED** [review]
🙏

**Comment by niekvanstaveren** [comment]
> Is there going to be another PR/s that move to GitHub Actions for the other jobs on CircleCI as well?

I'm not stopping you 😅 . Right now I am trying to move everything away from coveralls. Should not be too hard to move this one over I think

**Comment by cbt1** [comment]
> > Is there going to be another PR/s that move to GitHub Actions for the other jobs on CircleCI as well?
> 
> I'm not stopping you 😅 . Right now I am trying to move everything away from coveralls. Should not be too hard to move this one over I think

Thx 😛  My point was that why not just use CircleCI if there is no intention to move towards GitHub Actions

**Pull request merged**
